import { chromium } from 'playwright';
import path from 'path';
const OUT = decodeURIComponent(new URL('.', import.meta.url).pathname);
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1400, height: 1400 }, deviceScaleFactor: 2 });
await page.goto('file://' + path.join(OUT, 'compare.html'), { waitUntil: 'networkidle' });
await page.waitForTimeout(600);
await page.screenshot({ path: path.join(OUT, 'compare.png'), fullPage: true });
await browser.close();
console.log('done');
